### ISSUE TITLE
NoClassDefFound error

### ISSUE THREAD

**Issue by holcak** [enlivenhq/teamcity-slack#27]
Hi,

I've succesfully configured integration between TeamCity and Slack (I have applied all configuration steps), but no notification messages was succesfully sent to this moment. In Teamcity logs I've found errors (one error for each one attempt to send notification):

_WARN -   jetbrains.buildServer.SERVER - Exception occurred in notificator 
java.lang.NoClassDefFoundError: com/enlivenhq/teamcity/SlackPayload
	at com.enlivenhq.slack.SlackWrapper.getFormattedPayload(SlackWrapper.java:83)
	at com.enlivenhq.slack.SlackWrapper.send(SlackWrapper.java:41)
	at com.enlivenhq.teamcity.SlackNotificator.sendNotification(SlackNotificator.java:152)
	at com.enlivenhq.teamcity.SlackNotificator.notifyBuildSuccessful(SlackNotificator.java:66)
	at jetbrains.buildServer.notification.impl.UserRulesAwareNotificationListener$NotificatorEventAdapter.buildSuccessful(UserRulesAwareNotificationListener.java:280)
	at jetbrains.buildServer.notification.impl.UserRulesAwareNotificationListener.buildSuccessful(UserRulesAwareNotificationListener.java:64)
	at jetbrains.buildServer.notification.NotificationProcessor$2.call(NotificationProcessor.java:2)
	at jetbrains.buildServer.notification.NotificationProcessor$18.run(NotificationProcessor.java:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)_

My version of TeamCity is 9.1.6 (build 37459).
Am I missed some critical prerequisites? Does somebody know how can I proceed?

Thanks.

**Comment by cy6erskunk** [comment]
Hi @holcak, what's your teamcity-slack plugin version?
